#!/usr/bin/env php
<?php

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

$app = new Symfony\Component\Console\Application(
    'FusionCMS Installer', '1.3.1'
);

$app->add(new Efelle\FusionInstaller\RegisterCommand);
$app->add(new Efelle\FusionInstaller\TokenCommand);
$app->add(new Efelle\FusionInstaller\NewCommand);

$app->run();
