#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

$app = new Symfony\Component\Console\Application(
    'FusionCMS Installer', '1.0'
);

$app->add(new Efelle\FusionInstaller\RegisterCommand);
$app->add(new Efelle\FusionInstaller\TokenCommand);

$app->run();
